generator:
  image_encoder:
    stride: 3
    kernel_size: 5
    layer_1: 
      'in_channels': 3
      'out_channels': 1024
    layer_2:  
      'in_channels': 1024
      'out_channels': 512
    layer_3:  
      'in_channels': 512
      'out_channels': 512
    layer_4:  
      'in_channels': 512
      'out_channels': 256
    layer_5:  
      'in_channels': 256
      'out_channels': 256
    layer_6:  
      'in_channels': 256
      'out_channels': 128
    
  audio_encoder:
    layer_1: 
      'in_channels': 80
      'out_channels': 1024
      'kernel_size': 15
    
    layer_2:  
      'in_channels': 1024
      'out_channels': 512
      'kernel_size': 12
    
    layer_3:  
      'in_channels': 512
      'out_channels': 512
      'kernel_size': 8
    
    layer_4:  
      'in_channels': 512
      'out_channels': 256
      'kernel_size': 5
    
    layer_5:  
      'in_channels': 256
      'out_channels': 256
      'kernel_size': 3
    
    gru: 
      'input_size': 256
      'hidden_size': 128
      'num_layers': 1
    
  noise_generator: 
    'input_size': 10
    'hidden_size': 128
    'num_layers': 1
  