silence_length_crop: 500 # in ms
video_fps: 25
max_frames: 5000 # num of frames to read from intro
clip_min_len: 1000 # min clip len in ms
clip_max_len: 5000 # in ms
links: [
  "https://www.youtube.com/watch?v=PbN3HzKkW4M",
  "https://www.youtube.com/watch?v=3LWNY70Oj4A",
  "https://www.youtube.com/watch?v=EYIKy_FM9x0",
  "https://www.youtube.com/watch?v=oCkkjnpS2f8",
  "https://www.youtube.com/watch?v=n2RcVEftY48",
]